### ISSUE TITLE
Change definition of `refl` constructor in `Permutation.Heterogeneous` 

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1002]
At the moment it's `refl : Permutation R xs xs`. Although this looks fine, it's causing me severe problems as it breaks the size preserving property for various proofs involve `≋`. e.g. if `xs ≋ ys` and `ys ↭ zs` then the proof of `xs ↭ zs` is counter-intuitively much bigger than the proof of `ys ↭ zs` when it should be the same size.

To fix this I propose changing the definition of `refll` to `refl : Pointwise R xs ys →Permutation R xs ys`

**Comment by gallais** [comment]
I think we only have `Permutation.Homogeneous` but it would indeed make sense
to generalise it to `Permutation.Heterogeneous` and then generalise the type
of `refl` accordingly.

**Comment by JacquesCarette** [comment]
I've written extensive libraries dealing with permutations - `refl` should definitely have type `Permutation R xs ys`, always. From there, one ought to be able to prove that `xs` and `ys` are equal.  Otherwise, as @MatthewDaggitt says, the pain quickly becomes severe.  Very strongly in favour of this change.

**Comment by gallais** [comment]
Correcting myself: `Permutation` cannot possibly hetero because of `trans`.
