### ISSUE TITLE
Location of Everything.agda File

### ISSUE THREAD

**Issue by alexarice** [agda/agda-stdlib#1027]
Should Everything.hs be built into the `src` folder?

When I try to run agda on it I get the following error:
```
The name of the top level module does not match the file name. The
module Everything should be defined in one of the following files:
  /build/source/src/Everything.agda
  /build/source/src/Everything.lagda
  /nix/store/7nf4b2xzwv7mzdf3y8jry1gp4gdh698j-Agda-2.6.0.1-data/share/ghc-8.6.5/x86_64-linux-ghc-8.6.5/Agda-2.6.0.1/lib/prim/Everything.agda
  /nix/store/7nf4b2xzwv7mzdf3y8jry1gp4gdh698j-Agda-2.6.0.1-data/share/ghc-8.6.5/x86_64-linux-ghc-8.6.5/Agda-2.6.0.1/lib/prim/Everything.lagda
```
Perhaps there is a better way to use the `Everything.hs` file

**Comment by MatthewDaggitt** [comment]
I'm assuming you mean `Everything.agda` rather than `Everything.hs`. It's not part of the `src` folder because:
1. I can't think of a reason why anyone would ever actually want to import it?
2. it's a generated file and therefore shouldn't be under source control

If you want to type check everything in the library, you should probably use the `make test` command. Alternatively you can add `.` to the `standard-library.agda-lib` file underneath the `include` subtag.

**Comment by alexarice** [comment]
Apologies I did mean `Everything.agda`. I was trying to import it to compile all the files within, which I assumed was its purpose.

**Comment by alexarice** [comment]
Compiling with `-i .` worked for what I wanted to do so I will close the issue, thanks
