### ISSUE TITLE
Drop the dependency on `Data.Nat.Properties` from `Data.Fin.Base`? 

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1033]
If you want loading to get snappy, it's usually a good idea to use `.Base` rather
than the toplevel module because they are generally fairly self-contained.

For `Data.Fin.Base` however we need to typecheck the whole of `Data.Nat.Properties`
because of two functions:

```agda
fromℕ< : ∀ {m n} → m ℕ.< n → Fin n
inject≤ : ∀ {m n} → Fin m → m ℕ.≤ n → Fin n
```

This, in turns, means that `Data.List.Base` also depends on `Data.Nat.Properties`
and the same goes for everything depending on `Data.List.Base`.

I suggest that we move these two definitions to `Data.Fin`. The main hurdle being:
what should we do with the proofs involving these definitions? They are currently
in `Data.Fin.Properties` and cannot stay there as this would create a cycle
between `Data.Fin` and `Data.Fin.Properties`.

**Comment by JacquesCarette** [comment]
My first instinct is to move `≤-pred` out of `Data.Nat.Properties` and into `Data.Nat.Base`. That's where `≤` is defined, and `≤-pred` is arguably as much a computation as a proof transformer.  And that's the only function those two above require.

An alternative would be to create a `Data.Nat.Properties.Base` with just that one function in it.

**Comment by MatthewDaggitt** [comment]
Hmm so this was caused by #717. Prior to that we didn't need `Data.Nat.Properties` at all... For such a small change, that PR has had a lot of unintended side effects!

> I suggest that we move these two definitions to Data.Fin. The main hurdle being:
what should we do with the proofs involving these definitions?

I agree we don't have any pattern for dealing with properties of functions in the non-base module. Indeed I'd like to actively discourage us from adding things to them, as in v2.0 I'm hoping to start exporting far more stuff from the top-level modules, including other operations and properties. See #619.

> My first instinct is to move ≤-pred out of Data.Nat.Properties and into Data.Nat.Base. That's where ≤ is defined, and ≤-pred is arguably as much a computation as a proof transformer.

I'm also not terribly keen on this. Once you make an argument that `≤-pred` is a computation then in my mind we're on a slippery slope and it's very hard to justify not moving other stuff such as `suc-injective` from the `Properties` files.

> An alternative would be to create a Data.Nat.Properties.Base with just that one function in it.

This is definitely a possibility and I believe I've seen this pattern once or twice in the library before though I'm struggling to remember where.

Another alternative is to pre-emptively embrace #619 and move the `inject` and `fromℕ` lemmas out of `Data.Fin.Base` and into another module (`Data.Fin.Conversion` maybe?). This module would then be publicly exported by `Data.Fin` either now or in v2.0.

**Comment by JacquesCarette** [comment]
Has this converged to a conclusion? I'm on a refactoring kick, I'd be willing to do this.

One of the things I'm looking at is the dependency graph of the library, and seeing oddities. One reason to clean it up is to prevent future cyclic import nightmares. Another is that it does have an impact on load speed [but that is less important, at least right now.]

**Comment by MatthewDaggitt** [comment]
> Has this converged to a conclusion? I'm on a refactoring kick, I'd be willing to do this.

:tada: 

So if we were looking at releasing v2.0 I'd go for moving them `Data.Fin.Conversion`, but given that we're not my **new** cunning suggestion is simply to reimplement `≤-pred` in a private definition in `Data.Fin.Base`. Thoughts?

**Comment by gallais** [comment]
> reimplement `≤-pred` in a private definition in `Data.Fin.Base`. Thoughts?

Hopefully we will not need to mention that name in proofs about the functions
in question.

**Comment by JacquesCarette** [comment]
That last idea doesn't work:
```
/Users/carette/dev-agda-stdlib/src/Data/Fin/Properties.agda:402,48-76
ℕₚ.≤-pred le != Data.Fin.Base.≤-pred le of type n₁ ℕ.≤ n
when checking that the expression toℕ-inject≤ i (ℕₚ.≤-pred le) has
type toℕ (inject≤ i (Data.Fin.Base.≤-pred le)) ≡ toℕ i
```

**Comment by JacquesCarette** [comment]
Regarding a `.Base` for `Properties`, I think the precedent is `Data.List.Membership.Propositional.Properties.Core`.  I'll try that next.

**Comment by EdNutting** [comment]
This will impact #1217 - I can fix up my PR after this change goes through.
