### ISSUE TITLE
change the syntax of refinements from ∈ to :

### ISSUE THREAD

**Issue by riz0id** [agda/agda-stdlib#1061]
prefacing this issue by acknowledging my own pedanticism. i'm happy about the recent addition `Data.Refinement` however i think that the syntax is a little misleading:
```
infix 2 Refinement-syntax
Refinement-syntax = Refinement
syntax Refinement-syntax A (λ x → P) = [ x ∈ A ∣ P ]
```
here,  `∈` is a bit tricky because in type theory this would denote to a proposition. i propose that this be changed to `:`(`\:` in agda2 mode) since this expresses a predicate and a proof constructed from that predicate.

**Comment by MatthewDaggitt** [comment]
I'm not against that change. @gallais thoughts?

**Comment by riz0id** [comment]
sorry about strangeness in the issue. still trying to figure out this github thing.

**Comment by gallais** [comment]
No objection from me.

**Comment by riz0id** [comment]
in practice [`_,_`](https://github.com/agda/agda-stdlib/blob/c13613d9cb314dc6f217688e5c824bed63f5ae79/src/Data/Refinement.agda#L23) and [`[_]`](https://github.com/agda/agda-stdlib/blob/c13613d9cb314dc6f217688e5c824bed63f5ae79/src/Data/Erased.agda#L28) are also awkward to use since they collide with product's `_,_` and list's [`[_]`](https://github.com/agda/agda-stdlib/blob/c13613d9cb314dc6f217688e5c824bed63f5ae79/src/Data/List/Base.agda#L156). i'm not really sure what else to use here since there is no canonical notation for either erasure or refinements that i'm aware of.

**Comment by WolframKahl** [comment]
What is this anyways? In `Data.Refinement`, I read:
```
-- Refinement type: a value together with an erased proof.
```
I'd be tempted to say something like  “... with an erased proof for a property it has.”

But what does this have to do with refinement?

Even if these pairs are then subjected to refinement via the `refine` function below (which actually takes a more-refined pair as argument and produces a less-refined pair as result), I wouldn't call them refinements.

Since what is currently called `Refinement` there is just a variant of `Σ` with the second field erased, I would call it something like ` Σᵉ` and keep the field and constructor names the same as for `Σ`, just like `Vec` uses the same constructor names as `List`.

And if the containing module keeps its name `Data.Refinement`, then some justification for that at the beginning would be good.

(Explicit import lists for `Function.Base` and `Relation.Unary` would be good, too.)

**Comment by laMudri** [comment]
I strongly think this should be consistent across the library. In particular, whatever symbol is used here should also be used for [`Σ-syntax` from `Data.Product`](https://agda.github.io/agda-stdlib/Data.Product.html#916).

>in practice `_,_` and `[_]` are also awkward to use since they collide with product's `_,_` and list's `[_]`.

For `_,_`, I don't see why this is an issue. Both are constructors, so we can usually disambiguate. For `[_]`, I feel that it's `Data.List` which is at fault, because this also clashes with the inspect idiom from `Relation.Binary.PropositionalEquality` (where it is a constructor).

**Comment by MatthewDaggitt** [comment]
Any chance someone could put a PR together which makes the suggested change of more closely mimicking `Data.Product` in the next couple of days before the release of v1.3?

**Comment by laMudri** [comment]
Doesn't it already mimic `Data.Product`? Currently (on master):

```agda
infix 2 Refinement-syntax
Refinement-syntax = Refinement
syntax Refinement-syntax A (λ x → P) = [ x ∈ A ∣ P ]
```

The alternative would be changing everything from `∈` to `ː`.

**Comment by MatthewDaggitt** [comment]
Hmm okay maybe I don't understand the discussion in this issue! It looks like it's going to have to wait for v1.4 to make whatever adjustments are required. 

(I did consider trying to strip out `Data.Refinement` from `v1.3` but it looks like it's used by the new pretty printer so that's a no go).

**Comment by andreasabel** [comment]
Historical note: the original syntax for `\Sigma` was `\Sigma[ x \: A ] B` with said unicode colon.  @nad changed it to `\in` after a comment by Bengt Nordström that using a symbol that looks to the eye exactly like the `:` of type theory is very confusing.

In general, maybe one globally should not use two different unicode symbols that look the same to the eye of a reader.  We still want Agda code to be readable on paper.

Given that the discussion here has cooled, this issue could be closed maybe.

**Comment by MatthewDaggitt** [comment]
> Given that the discussion here has cooled, this issue could be closed maybe.

Given that:
1.  the original comment was nitpick
2. it does currently agree with the syntax used in `Data.Product`
3. as @andreasabel says we should try and avoid using unicode characters that can't be indistinguished by eye.
4. it can no longer be changed in a backwards compatible manner.
I agree, closing.
