### ISSUE TITLE
Error after running `fix-agda-whitespace`

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#1135]
After running `fix-agda-whitespace`, I got the error:

```
$ make test
...
agda +RTS -M3.5G -H3.5G -A128M -RTS -i. -isrc README.agda
 Checking README.Text.Tabular (/some-path/README/Text/Tabular.agda).
/some-path/README/Text/Tabular.agda:106,5-9
"foo bar\n  1 2  \n  4 3  " != "foo bar\n  1 2\n  4 3  " of type
String
when checking that the expression refl has type
unlines (Tabularᵛ.display whitespace (Right ∷ Left ∷ []) foobar) ≡
"foo bar\n  1 2\n  4 3  "
```

**Comment by asr** [comment]
The file `README/Text/Tabular.agda` should be excluded in `fix-whitespace`. I'll try exclude it.

**Comment by asr** [comment]
The error was because I used `fix-agda-whitespace` instead of `fix-whitespace`.

**Comment by gallais** [comment]
See the [HACKING.md](https://github.com/agda/agda-stdlib/blob/master/HACKING.md#how-to-enforce-whitespace-policies) file.

We are now using `fix-whitespace` and explicitly whitelisting a bunch of files
that have whitespace because they contain code with meaningful whitespace
generated by `Text.Tabular`

**Comment by asr** [comment]
I included the `*.md` to be tested.
