### ISSUE TITLE
Travis doesn't appear to use Agda 2.6.1 on `master`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1243]
Anyone know why we do not seem to be using Agda v2.6.1 in Travis when testing `master`?

https://github.com/agda/agda-stdlib/blob/979c0650d2ce5eb6bae9ec359bacf72c2dde25df/.travis.yml#L47-L52

It seems to be causing a test failure in #1242

**Comment by JacquesCarette** [comment]
That particular commit was put in to `.travis.yml` by @jespercockx .  It is indeed odd that tags aren't used for checkout.

**Comment by EdNutting** [comment]
I see two issues here:

1. The inconsistency as to which version of Agda the stdlib is being tested against (which doesn't align with the Agda release branches

2. Why did the build start failing on 28th June when it was working on 22nd June with exactly the same commit checked out? The error message says `toJSONList` isn't in scope - perhaps a dependency has changed signature?

**Comment by gallais** [comment]
> That particular commit was put in to `.travis.yml` by jespercockx.

IIRC there used to be a problem in the way in which Agda deals with
aliases with no type declaration that led to unsolved metavariables.
I knew something similar had been fixed recently so I mindlessly
suggested using a newer commit without realising that should mean
targeting `experimental`. The issue was here:

https://github.com/agda/agda-stdlib/pull/1096#issuecomment-595192896

I think we would have to revert the addition of these instances and
move them to `experimental` instead to be able to move back to 2.6.1.
I can prepare the PRs if you want.

> It is indeed odd that tags aren't used for checkout.

Good idea.

**Comment by MatthewDaggitt** [comment]
> I can prepare the PRs if you want.

If you could, that'd be awesome 👍

**Comment by gallais** [comment]
Fixed by 38c2b2ce9a20d67563a6cfd243ad4acab9e736cb
