### ISSUE TITLE
Tactic.RingSolver doesn't work with multiplication

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#1318]
```agda
module MinimalFailing where

open import Data.Integer
open import Data.Integer.Tactic.RingSolver
open import Relation.Binary.PropositionalEquality

works : ∀ x y → x + y ≡ y + x
works = solve-∀

doesn'twork : ∀ x y → x * y ≡ y * x
doesn'twork = {! solve-∀ !}
```

If I try to fill in that hole, I get this error:

```
/home/taneb/Documents/Agda/antlion/src/MinimalFailing.agda:11,17-24
Tactic.RingSolver.Core.Expression.Expr
(Tactic.RingSolver.Core.AlmostCommutativeRing.AlmostCommutativeRing.Carrier
 ring)
2
!=< ℤ
when checking that the expression x has type ℤ
```

I would expect this, and more complicated examples involving multiplication, to work.

**Comment by oisdk** [comment]
Generally to use the solve you need to use the definitions bound in the `AlmostCommutativeRing` record, i.e.:

```agda
open import Data.Integer.Tactic.RingSolver
open import Relation.Binary.PropositionalEquality

open import Tactic.RingSolver.Core.AlmostCommutativeRing using (AlmostCommutativeRing)
open AlmostCommutativeRing ring

works : ∀ x y → x + y ≡ y + x
works = solve-∀

also-works : ∀ x y → x * y ≡ y * x
also-works = solve-∀
```

Now, if you use definitions that *aren't* from the record, then the ring solver will still try its best to figure out what the operation is, by evaluating the record entry and comparing it to each function in the expression. That works for `_+_` on `ℤ` here, because the definition of `_+_` is:

```agda
_+_ : ℤ → ℤ → ℤ
-[1+ m ] + -[1+ n ] = -[1+ ℕ.suc (m ℕ+ n) ]
-[1+ m ] + +    n   = n ⊖ ℕ.suc m
+    m   + -[1+ n ] = m ⊖ ℕ.suc n
+    m   + +    n   = + (m ℕ+ n)
```

So it can't reduce, since it does pattern matching, so the solver can see that this function is the same as the function referred to in the `AlmostCommutativeRing` record. For `_*_`, on the other hand, the definition *can* reduce:

```agda
_*_ : ℤ → ℤ → ℤ
i * j = sign i S* sign j ◃ ∣ i ∣ ℕ* ∣ j ∣
```

And the solver can't deduce that this expression is equal to the multiplication defined in the record `AlmostCommutativeRing` record.

**Comment by MatthewDaggitt** [comment]
Thanks for the detailed reply @oisdk. At the very least we should document this shortcoming in `Data.Integer.Tactic.RingSolver`. 

It's also quite a big problem. I'm guessing most people won't be looking to prove expressions about the operators from the constructed ring. I don't have any particularly good ideas about how to fix it either, unless the macro can request that Agda doesn't normalise the terms before passing them in. No idea how practical that is though...

**Comment by jespercockx** [comment]
> I don't have any particularly good ideas about how to fix it either, unless the macro can request that Agda doesn't normalise the terms before passing them in. No idea how practical that is though...

Tactics can use the `withNormalization` primitive to turn on/off normalization of terms. In the next version of Agda, you'll also be able to use `onlyReduceDefs` and `dontReduceDefs` to include or exclude specific definitions to unfold or not unfold.

**Comment by MatthewDaggitt** [comment]
Thanks @jespercockx, that sounds pretty promising!

**Comment by MatthewDaggitt** [comment]
Okay I've had a crack at this and the problem is *way* harder than I thought. @jespercockx unfortunately I don't think either `withNormalization` or `onlyReduceDefs` or `dontReduceDefs` digs us out of this hole.

Suppose we're trying to identify the concrete instance of the field `AlmostCommutativeRing._*_` which happens to be ultimately `Data.Integer._*_` which in turn is ultimately defined in terms of some function `f`. Then we have the following chain of normalisations:
```
AlmostCommutativeRing._*_
.... 
Data.Integer._*_ 
....
f
````
Because we don't know what the `....`s are, or indeed what `Data.Integer._*_` is then we can't use `onlyReduceDefs` or `dontReduceDefs` to stop in the right place.

The only approach I can think that might work is if we normalise both expressions all the down and then compare equality at the term level rather than trying to compare definition names. Going to give that a shot and see how it goes...

**Comment by MatthewDaggitt** [comment]
Normalising everything works :tada:
