### ISSUE TITLE
what is symmetric version of ``≈⟨`` ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1330]
Please, what is the symmetric version of  ``≈⟨`` 
(in equational beasoning with ``begin ...``) ?
Where it is used in lib-1.4 ?

**Comment by MatthewDaggitt** [comment]
https://github.com/agda/agda-stdlib/blob/d7d3d69042011dafa0587578448b595522704bae/src/Relation/Binary/Reasoning/PartialSetoid.agda#L37

i.e. `≈˘⟨ ... ⟩` rather than `≈⟨ ... ⟩`. As for uses you can look using grep or the Github search functionality.

By the way this would have been more appropriate as a question on my comment in your PR rather than opening a new issue for it.
