### ISSUE TITLE
`_/_` signature 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1420]
Looking at the signature of  
```
_/_ : (dividend divisor : ℕ) {≢0 : False (divisor ≟ 0)} → ℕ  
```
in Data.Nat.DivMod,  and given  ``n≢0 : n ≢ 0``,
how to obtain the quotient  ``4 / n`` ?
what argument to add?
May be it is better not to force the reader/user to investigate in `False`, `T`, and in such brain twisting things?
They appear somewhat out of nothing.
For example, it is possible  
```
[_/_,_] : ℕ → (n : ℕ) → n ≢ 0 → ℕ
```
, so that the call is  ``[ m / n , n≢0 ]``.
And probably it is better  ``quot : ℕ → (n : ℕ) → n ≢ 0 → ℕ``
For example, ``(quot m n n≢0) * k``.
Similar it is with `mod` (or `rem`).
?

**Comment by MatthewDaggitt** [comment]
The documentation above the definition describes why it is defined like this:

https://github.com/agda/agda-stdlib/blob/fbe42635d0eec306c0d338260360898aa989acf9/src/Data/Nat/DivMod.agda#L30

To get from `n ≢ 0` to `False (divisor ≟ 0)` use `fromWitnessFalse` from `Relation.Nullary`

https://github.com/agda/agda-stdlib/blob/fbe42635d0eec306c0d338260360898aa989acf9/src/Relation/Nullary/Decidable/Core.agda#L73

See #921 about how division and modulus are going to be redesigned in version 2.0 of the library. You will then be able to use the `nonZero` constructor from `Data.Nat` instead of `fromWitnessFalse` which should make it more much more intuitive to use:

https://github.com/agda/agda-stdlib/blob/fbe42635d0eec306c0d338260360898aa989acf9/src/Data/Nat/Base.agda#L99
