### ISSUE TITLE
Why is module XorRing in Algebra.Properties.BooleanAlgebra parameterised?

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#144]
If you ever need to reparameterise the resulting ring then that should be done in the general case by separate lemmas?

**Comment by andreasabel** [comment]
I think only @nad can answer this.

**Comment by nad** [comment]
I don't understand the question.

**Comment by MatthewDaggitt** [comment]
The current prelude looks like this:
```agda
module XorRing
  (xor : Op₂ Carrier)
  (⊕-def : ∀ x y → xor x y ≈ (x ∨ y) ∧ ¬ (x ∧ y))
  where

  private
    infixl 6 _⊕_

    _⊕_ : Op₂ Carrier
    _⊕_ = xor
```
I was just interested why it's not:
```agda
module XorRing where

  infixl 6 _⊕_

  _⊕_ : Op₂ Carrier
  _⊕_ = (x ∨ y) ∧ ¬ (x ∧ y)
```

Xor is defined for any `BooleanAlgebra` so do you need to pass in a definition? The only reason that I can think of is if you need to change the additive or multiplicative parametrisation of the resulting `Ring`. However I would have thought that should be more generally over all `Ring`s via a `replace-addition` or `replace-multiplication` lemmas, similar to the existing `replace-equality` lemmas.

It would also take 20-25 lines out of the proofs.

**Comment by WolframKahl** [comment]
> Xor is defined for any `BooleanAlgebra` so do you need to pass in a definition?

Not for the purpose of just having it defined.

But for the purpose of having a `XorRing` where `xor` is defined more efficiently than by
````agda
xor x y = (x ∨ y) ∧ ¬ (x ∧ y)
````
this pattern is useful.

I don't know whether this was part of the original motivation here, but I am employing this pattern myself in several places (so far mostly only where I need it).

I see this as part of the tension between minimal interfaces for economy of reasoning, and  maximal interfaces (including what otherwise would be derived definitions as axioms) for the purpose of enabling specialised implementations. In the places where I use this, I have a module containing default definitions, so that the new Agda feature allowing record fields to be supplied by modules makes it cheap to to produce instances for the large interface by supplying definitions only for the small interface. And I consider the cost of additional fold/unfold proof steps inside the module with those additional parameters as tolerable, even though it is certainly a nuisance at the time of converting a derived definition into parameters.

**Comment by MatthewDaggitt** [comment]
> But for the purpose of having a XorRing where xor is defined more efficiently than by
> ```xor x y = (x ∨ y) ∧ ¬ (x ∧ y)```
> this pattern is useful.

That's interesting! When you say "efficiently" what do you mean? Efficient in terms of definition size? In type checking time? In execution time?

> I see this as part of the tension between minimal interfaces for economy of reasoning, and maximal interfaces (including what otherwise would be derived definitions as axioms) for the purpose of enabling specialised implementations.

I agree that there is definitely a trade-off and LoC saving is certainly not desirable if it comes at the cost of usability. The library should be aiming to make users' lives as easy as possible!

> In the places where I use this, I have a module containing default definitions, so that the new Agda feature allowing record fields to be supplied by modules makes it cheap to to produce instances for the large interface by supplying definitions only for the small interface. And I consider the cost of additional fold/unfold proof steps inside the module with those additional parameters as tolerable, even though it is certainly a nuisance at the time of converting a derived definition into parameters.

Hypothetically, if I'm understanding you correctly, the `replace-addition` and `replace-multiplication` lemmas would be an alternative way of obtaining the same effect? All proofs would be done with the "standard" definition and then the "efficient" definition could be substituted in afterwards? (Although I feel that if they don't have the same effect, the lemmas would still be useful to have anyway).

I guess I'm just bemused about the fact that in the current configuration, despite the library having a whole module of proofs about it, the user doesn't actually have access to an definition of `xor`!

**Comment by WolframKahl** [comment]
> When you say "efficiently" what do you mean? Efficient in terms of definition size? In type checking time? In execution time?

For my main use cases, this is efficient in terms of execution time.

However, I can also imagine uses where reasoning about specialised instances becomes easier due to the non-derived definitions which are then directly visible (via definitional equality).


> > In the places where I use this, I have a module containing default definitions, so that the new Agda feature allowing record fields to be supplied by modules makes it cheap to to produce instances for the large interface by supplying definitions only for the small interface. And I consider the cost of additional fold/unfold proof steps inside the module with those additional parameters as tolerable, even though it is certainly a nuisance at the time of converting a derived definition into parameters.
>
> Hypothetically, if I'm understanding you correctly, the `replace-addition` and `replace-multiplication` lemmas would be an alternative way of obtaining the same effect? All proofs would be done with the "standard" definition and then the "efficient" definition could be substituted in afterwards? (Although I feel that if they don't have the same effect, the lemmas would still be useful to have anyway).

In a fresh agda-stdlib clone,
````sh
 $ grep replace- $(find . -name "*.agda")
````
only finds `replace-equality`, so I can only guess for `replace-addition` and `replace-multiplication`.

I think that in general, these `replace-` lemmas would have the same effect for reasoning where definitional equality does not matter.

However, where proofs are not irrelevant, which includes for typechecking, the adaptions-throughout in these `replace-` lemmas will have costs that matter. And where it's replacing operations, some derived operations might become or remain unexpectedly more expensive at run-time.

But I agree that these `replace-` lemmas would still be useful to have anyway.

> I guess I'm just bemused about the fact that in the current configuration, despite the library having a whole module of proofs about it, the user doesn't actually have access to an definition of `xor`!

(Before the record-fields-from-modules feature, I would probably have been hesitant to actually write something as simple as the `xor-default` definition you presumably have in mind, and from that perspective can understand its absence.)

**Comment by nad** [comment]
> I was just interested why it's not: [...]

It appears as if I wrote the code in this way because I wanted to use a specific implementation of exclusive or for booleans, see `Data.Bool.Properties.commutativeRing-xor-∧`.

**Comment by MatthewDaggitt** [comment]
> However, where proofs are not irrelevant, which includes for typechecking, the adaptions-throughout in these replace- lemmas will have costs that matter. And where it's replacing operations, some derived operations might become or remain unexpectedly more expensive at run-time.

I definitely agree that such lemmas will have a computational cost. However, maybe I'm not understanding correctly, but I'm still struggling to see why the current solution side-steps that problem. Surely exactly the same cost is already incurred by the constant use of the translation lemma `⊕-def : ∀ x y → xor x y ≈ (x ∨ y) ∧ ¬ (x ∧ y)` throughout the proofs in the module? As far as I see the only thing my proposed `replace-addition` etc. lemmas would be doing is to generalise this translation stage out of this very specific case, and allow it to be used more generally.

Anyway, no worries. I won't be touching this anytime soon! I was just curious as to why it's implemented as it is.

**Comment by MatthewDaggitt** [comment]
Closing as my question has been answered and the conversation has ended.
