### ISSUE TITLE
Deprecate or refactor `Algebra.Construct.Subst.Equality`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1445]
This can now be implemented entirely via `Algebra.Morphism`

**Comment by jamesmckinna** [comment]
So it seems as though `Algebra.Morphism` ended up deprecated, and `Subst.Equality` lived to fight another day... so close this now?

**Comment by MatthewDaggitt** [comment]
I should have been more precise. It can be implemented by the classes below `Algebra.Morphism`...

**Comment by jamesmckinna** [comment]
Ah! ... thanks for the signpost... and for revisiting a dormant issue... worth knocking off for v2.2?

**Comment by MatthewDaggitt** [comment]
As always, if someone is willing to do it :smile:

**Comment by JacquesCarette** [comment]
I'll give it a try.

**Comment by JacquesCarette** [comment]
So I don't think this is going to be an improvement. The old code looked like https://github.com/agda/agda-stdlib/blob/d5bb6cfb2fd278e941cc16efcb33a1faf39c133b/src/Algebra/Construct/Subst/Equality.agda#L68-L72 but now one has to do
```agda
isMagma : ∀ {∙} → IsMagma ≈₁ ∙ → IsMagma ≈₂ ∙
isMagma {∙} S = MagmaMor.isMagma Mor S
  where
    M₁ : RawMagma a ℓ₂
    M₁ = record { _≈_ = ≈₂ ; _∙_ = ∙ }
    M₂ : RawMagma a ℓ₁
    M₂ = record { _≈_ = ≈₁ ; _∙_ = ∙ }
    Mor : MagmaMorphisms.IsMagmaMonomorphism M₁ M₂ id
    Mor = record
      { isMagmaHomomorphism = record
        { isRelHomomorphism = record { cong = from }
        ; homo = λ _ _ → IsMagma.refl S
        }
      ; injective = to
      }
```
where `MagmaMor` is `Algebra.Morphism.MagmaMonomorphism`, where we have https://github.com/agda/agda-stdlib/blob/d5bb6cfb2fd278e941cc16efcb33a1faf39c133b/src/Algebra/Morphism/MagmaMonomorphism.agda#L101-L105
which looks perfect for the job.

The problem, as seen above, is twofold:
1. that morphism (`Mor`) above is *not* the identity morphism (as defined in `Algebra.Morphism.Construct.Identity`) because that one is monomorphic in its equivalence, but here we keep two things (carrier and binary operation) the same but change the equivalence relation.
2. constructing that morphism requires that we build the two RawMagmas, because that's what it wants, not `IsMagma`.

It only gets progressively worse with richer structures.

It seems that slight impedance mismatches make what in theory a good idea, seems more like a step backwards in practice.

**Comment by MatthewDaggitt** [comment]
Okay, thanks for investigating. Will close this issue then!
