### ISSUE TITLE
IO usage in lib-1.6-rc1

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1473]
In lib-1.5, I use  output like this:
```
open import Codata.Musical.Costring using (toCostring)
open import Data.String  using (String)
open import Data.Unit  using (⊤)
open import Foreign.Haskell
open import IO.Primitive    
{-  now ??
open import IO  using (IO; readFiniteFile;  writeFile∞; appendFile∞;  putStr∞; putStrLn∞ )
-}
open import Data.Nat.Show using () renaming (show to showℕ) 

open import List.I using (concatStr)  -- of application 

main : IO ⊤
main = putStrLn (toCostring (showℕ 203))               
```
This is not type checked with  lib-1.6-rc1.
Please, how to fix?
How to set this import in a cultural way?

**Comment by gallais** [comment]
> This is not type checked with lib-1.6-rc1.

This is not a very useful bug report. The exact error message would
be more useful.

Looking at the code, I guess you were using the primitives directly
rather than `IO`?! This ought to work:

```agda
main : Main
main = run $ putStrLn (showℕ 203)
```

**Comment by mechvel** [comment]
Thank you. I shall try this.

> This is not a very useful bug report. 

This is not about a bug. Matthew has invited notes on lib-1.6-rc1 to be posted on GitHub. 
Right?
As there is a change in the IO part due to which my program is broken, I asked about a new way of organizing
IO things, in particular, about fixing this concrete code.

**Comment by MatthewDaggitt** [comment]
No, this was the correct replace to report it. But when you report something breaks, you should always provide the error message as well. That help's us isolate the problem. Particularly as your example has external dependencies which we have no access to.

As @gallais said, the problem was that you were importing `IO.Primitive` rather than `IO`. We don't make any guarantees about the interface of `.Primitive` modules staying the same. I've attempted to improve the documentation in #1479.

**Comment by mechvel** [comment]
renaming ( writeFile  to writeFile∞; ...                                
                     putStrLn   to putStrLn∞
