### ISSUE TITLE
Confusing old git tags starting with v2.5

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda-stdlib#1574]
Can we delete or rename the old tags starting with `v2.5`, given that they clash with the present versioning scheme? They are slightly confusing and give the impression that there is no release for Agda 2.6.

**Comment by MatthewDaggitt** [comment]
I regularly delete them, both here and in my local repo, but someone keeps pushing them back up? I can't work out who... Do you have any ideas about how to stop that?

**Comment by ajrouvoet** [comment]
Perhaps it makes sense to limit who is allowed to push tags to a small group?

**Comment by MatthewDaggitt** [comment]
Hmm the problem is that the permissions are shared over the `Agda developer` group and it's not easy to separate out the permissions to apply only to this repo. I've deleted them again, and made sure they don't exist in my local repo. In theory that should do it, as I'm the only one who creates tags but :shrug: Please re-open if they reappear once again, and then we can investigate messing around with making the permissions more fine-grained.
