### ISSUE TITLE
Association lists and their functions

### ISSUE THREAD

**Issue by Saransh-cpp** [agda/agda-stdlib#2048]
I am currently looking to port [`lookup`](https://github.com/idris-lang/Idris2/blob/badf1e98c8812e8b54258754cf47782f61d8fb15/libs/base/Data/List.idr#L184-L185), [`lookupBy`](https://github.com/idris-lang/Idris2/blob/badf1e98c8812e8b54258754cf47782f61d8fb15/libs/base/Data/List.idr#L174-L180), [`insertAt`](https://github.com/idris-lang/Idris2/blob/badf1e98c8812e8b54258754cf47782f61d8fb15/libs/base/Data/List.idr#L228-L230), and [`deleteAt`](https://github.com/idris-lang/Idris2/blob/badf1e98c8812e8b54258754cf47782f61d8fb15/libs/base/Data/List.idr#L241-L243) from  Idris2, but I am not sure if they are exactly required in Agda. It does look like that they do not exist in Agda. If they should be added in, should the API of `lookup` and `lookupBy` stay the same, or should it be changed (given that I could not find any such pair of functions in Agda)? Thanks!

**Comment by jamesmckinna** [comment]
`deleteAt` appears to be the `_─_` operation? 

No answer to why there isn't (?) the companion `insertAt` (though there is in `Data.Vec.*` etc. I think ... this may be yet another knock-on consequence of `List` and `Vec` not being mutually consistent)

As for association lists themselves, I'd be tempted to organise them under `Data.List.Association.*` rather than try to shoehorn them into `Data.List.Base`? They're a distinguished mode of use of lists, satisfying the finite Map API, and that little theory seems worth abstracting out on its own? Just my opinion, though!

**Comment by jamesmckinna** [comment]
As to the question about API design, as a precursor to eventual implementation, should we consider more deliberately discussing those as separate issues/PRs/threads on the Zulip (under the #stdlib channel?)

**Comment by jamesmckinna** [comment]
And now returning to the main question: how much of `idris2`'s (or that of any classical/orthodox Boolean-valued/simply-typed approach) behaviour on association lists can be realised in terms of the `...Relation.Unary.Any` machinery, suitably specialised? Question prompted by threading back through the definitions in `Data.List.Membership` etc.

if it is possible to 'encode everything' that way, that doesn't stop it being independently interesting to consider versions specialised to lists of pairs, where the 'unary' predicate on pairs is given by ... a binary, Boolean-valued function.

**Comment by Saransh-cpp** [comment]
I think I forgot to post a reply here yesterday (I remember I wrote one 😬)

> deleteAt appears to be the _─_ operation?

I missed that! Thanks!

> this may be yet another knock-on consequence of List and Vec not being mutually consistent

I found a lot of such inconsistencies yesterday. For instance, starting with the insert, delete, and update operations, `Vec` and `List` have some of them as functions and some of them as mixifx operators making it very inconsistent -
- `Vec` has both a function and a mixifix operator for updating an element using a function (`updateAt` and `_[_]%=_`), `List` has only the mixfix operator
- For removing an element, `Vec` only has `remove`, on the other hand, `List` has a mixfix operator `_─_`, making this also inconsistent with the "update" function and operator
- For insertion, `Vec` has `insert` and `List` has nothing.
```agda
insert : Vec A n → Fin (suc n) → A → Vec A (suc n)
remove : Vec A (suc n) → Fin (suc n) → Vec A n  -- similar to _─_ in List
updateAt : Fin n → (A → A) → Vec A n → Vec A n
_[_]%=_ : Vec A n → Fin n → (A → A) → Vec A n  -- this is updateAt, but as a mixfix operator
_[_]≔_ : Vec A n → Fin n → A → Vec A n -- overwrites the i-th element of xs with y
```

```agda
_[_]%=_ : (xs : List A) → Fin (length xs) → (A → A) → List A  -- similar to Vec, but does not have the updateAt function
_[_]∷=_ : (xs : List A) → Fin (length xs) → A → List A  -- similar to Vec
_─_ : (xs : List A) → Fin (length xs) → List A  -- similar to remove in Vec, but List does not have a remove function
```
I'll start by making these 3 functions and their corresponding mixfix operators consistent.

---

Reading your thoughts about association lists, I think it is more complicated to add them to Agda than I had initially thought 🙂

I read about association lists and if I understood your comments, association lists do not exist in Agda? So this would require formalising the idea and API of association lists in Agda before actually writing those functions.

**Comment by MatthewDaggitt** [comment]
See https://github.com/agda/agda-stdlib/pull/1552 for a discussion of an aborted attempt of designing a similar interface for priority queues.

**Comment by jamesmckinna** [comment]
Regarding @MatthewDaggitt 's comment: my own instincts are also towards a wide user-facing API, with a narrower implementor-facing API, not least because we are/have become more sophisticated about 'smart constructor' approaches to bootstrapping from narrow to wide...

But in some sense, the API design question (and any subsequent PR) can, conceptually at least, be uncoupled from implementation... even if any particular experiment will probably ping-ping iteratively between the two! The challenge of collaborative software development might be to remain, as far as possible, as flexible/ego-less as regards API revision, as possible. Mind you, that's rich coming from me!

**Comment by JacquesCarette** [comment]
So I looked at `Any` in relation to this, and I get the feeling that it is 'backwards' in the sense that if you have an `Any` in your hands, you already have the answer you seek with doing a `lookup` in an association list. So what would be the point?

The main point of this issue is to ask: should agda-stdlib have association lists? That exact structure, rather than the wider question of designing a generic API for key-value stores.

**Comment by JacquesCarette** [comment]
To go to things said way back at the start of this thread: I'm explicitly choosing to discuss this on issues here, so that there is written record of the discussion (and ultimately the results of that discussion) that can easily be searched in the future.

I'm not sure if enough of the designers of stdlib spend enough time on the Zulip to have a 'better' conversation there. Ultimately, it is the quality of the conversation that matters most.

**Comment by jamesmckinna** [comment]
@JacquesCarette thanks for the nudge use of the issue tracker for these open-forum discussions. Against myself, I  perhaps even agree that the Zulip might not be the right place, although it (and other Zulip instances) is where I spend a lot of time online these days, outside my own contributions to development here.

**Comment by jamesmckinna** [comment]
To the discussion topic then: my understanding is that we don't have association lists *per se* in the library.

If they are to be added, I might think under `Data.List.Association.Base` and `Data.List.Association.Properties`, with some possible axes in the design space to consider:
* vanilla `key × value` pairs stored in the lists, or something more interesting? (eg should values be able to depend on keys?)
* types in the 'basic' API: haskell-like ('haskellic'? 'haskeletal'?) as in #2042 , or more dependently-typed/richly articulated? (in an ideal world, we might seek PRs offering each extreme, and cherry-pick the best-of-breed?)
* what properties do we want?

This, in turn, might generate, here or as a separate issue/PR, an API ... (oh, I can be very top-down as a designer, can't I?)... and once we agree, a PR implementing it. But then @MatthewDaggitt 's mention of #1552 and #1542 and earlier discussions about narrow/wide API design come to the fore...

... but would you (two) like to start the ball rolling? (no pressure, express or implied)

**Comment by jamesmckinna** [comment]
Another one to punt until after v2.0, I think ;-)

**Comment by JacquesCarette** [comment]
I agree, this seems quite stale. I will have another student working on stdlib this summer. Still, this may not be the highest priority then either.
