### ISSUE TITLE
Choice of pre/post-condition combinators in proof names

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2168]
CHANGELOG.md  in  lib-2.rc1  writes  
```
reflexive+selfInverse⇒involutive  : ...
```
In other places (in lib-1.7.2),  I recall,  `∧`  is used  in similar situations in the name, probably, in Data.Nat.Properties  ...
It is also reasonable to use comma.
And `+` presumes a different meaning in  the names like  ``m≤n+n``.
Anyway it has sense to choose a uniform denotation for the library.

**Comment by MatthewDaggitt** [comment]
Hmm yes this is a good point. In the [style guide](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md#preconditions-and-postconditions) it says:

> Preconditions and postconditions should be combined using the symbols ∨ and ∧ (e.g. m*n≡0⇒m≡0∨n≡0)

but we certainly haven't been enforcing this to date.

**Comment by jamesmckinna** [comment]
Indeed, the cited example at the top of the issue is mine, but was written to emulate those already extant in `Algebra.Consequences`, where the use of `+` rather than `∧` seems to have been the conventional, if not the mandated style. 

If there's time, I'll try to look at this, but I suspect it will be quite a deprecation headache, so my personal prefernce would be to push this kind of administrative naming change to v2.1 or v3.0.
