### ISSUE TITLE
Using String as a key in an AVL tree

### ISSUE THREAD

**Issue by siddharthist** [agda/agda-stdlib#256]
Hi, I'd like to use `String` as a key in an AVL tree. `String` has an instance of `StrictTotalOrder`, but it still can't be used because the underlying notion of equality isn't Agda's builtin. When I try this:
```
primitives : Tree {Key = String}            -- Key
                  (λ _ → List Lisp → Lisp)  -- Value
                  (isStrictTotalOrder String.strictTotalOrder)
```
I get this:
```
.Relation.Binary.List.Pointwise.Rel
(_≈_ .Data.Char.strictTotalOrder) (String.toList x)
(String.toList x)
!= x .Agda.Builtin.Equality.≡ x of type Set
when checking that the expression
isStrictTotalOrder String.strictTotalOrder has type
Relation.Binary.IsStrictTotalOrder .Agda.Builtin.Equality._≡_
__<__9
```
The following also doesn't work for `List Char`:
```
 (isStrictTotalOrder (StrictLex.<-strictTotalOrder Char.strictTotalOrder))
```
I get this message:
```
/home/siddharthist/code/agda-scheme/Eval.agda:20,9-80
.Relation.Binary.List.Pointwise.Rel (_≈_ Char.strictTotalOrder) x x
!= x .Agda.Builtin.Equality.≡ x of type Set
when checking that the expression
isStrictTotalOrder (<-strictTotalOrder Char.strictTotalOrder) has
type
Relation.Binary.IsStrictTotalOrder .Agda.Builtin.Equality._≡_
__<__10
``` 
Indeed, one can't even use `Char.strictTotalOrder`, which relies on equality of `Nat`s. Could the condition on the underlying equivalence relation be abandoned?

I have Agda version 2.5.3, and am testing with commit 7220ca3ee025e9339aa8e5d11efcd069764e7977.

**Comment by MatthewDaggitt** [comment]
Yes, this is an excellent suggestion. @gallais do you think you might have time to change it at some point? I'm happy to do it myself if not, but you might be much quicker at it given that you rewrote the implementation in 0.15...

**Comment by gallais** [comment]
Sure. Btw this is a common issue and here's a workaround that should work with the current library: https://stackoverflow.com/questions/36269333/agdas-standard-library-data-avl-sets-containing-data-string-as-values

**Comment by gallais** [comment]
This is a bit subtle. I actually encountered a similar issue when defining 2-3 Trees
in Idris for https://github.com/gallais/idris-tmustache:

When you have `k = k'` propositionally, you can use either one seamlessly because
you can use the identity to cast one ot the other.

*However*, once you decide to use any other equivalence relation it's not the case.
Which makes implementing functions such as `insertWith` harder. Cf. the use of
[`rewrite P.sym k≡k′`](https://agda.github.io/agda-stdlib/Data.AVL.Indexed.html#9426) for instance.

One possibility is to change the type of `insertWith` from:

```agda
 ∀ {l u h} → (k : Key) → V k →
               (V k → V k → V k) →  -- New → old → result.
               Tree V l u h → l < k < u →
               ∃ λ i → Tree V l u (i ⊕ h)
```

to

```agda
∀ {l u h} → (k : Key) → V k →
               (∀ k′ → k ≈ k′ → V k → V k′ → V k′) →  -- New → old → result.
               Tree V l u h → l < k < u →
               ∃ λ i → Tree V l u (i ⊕ h)
```

And then `insert` can only be defined if we have: `cast : ∀ k′ → k ≈ k′ → V k → V k′`

Similarly `lookup` is broken: we can only hope to return `Maybe (Σ[ k′ ∈ Key ] k ≈ k′ × V k′)`
instead of `Maybe (V k)`.

Of course, a lot of these functions get a nicer type if we assume that `∀ k k′ → k ≈ k′ → V k ≡ V k′`
(which is the case in the non-indexed case so we could still offer a nice `Set` interface).

**Comment by MatthewDaggitt** [comment]
Sorry it's taken so long to reply to this.

The assumption `cast : ∀ k′ → k ≈ k′ → V k → V k′ seems like a very natural thing to have. If it makes life easier, I think it would even be reasonable to make it a module parameter. After all, it's a strictly weaker assumption then the current implementation that assumes propositional equality.

Would that be sufficient to make everything go through?

**Comment by bch29** [comment]
I think it would make more sense to provide the general interface (in addition to the casting one as a specialization) to make this useful to more people. Unless there's a particular roadblock to implementing the general interface?
