### ISSUE TITLE
Remove ⊆-Reasoning?

### ISSUE THREAD

**Issue by nad** [agda/agda-stdlib#310]
There are three submodules called `⊆-Reasoning` in the library. I suspect that at least one of them could be removed.

**Comment by MatthewDaggitt** [comment]
So @alhassy and I had a look at this and in the end all three of them are needed. The one in `BagAndSetEquality` is over a different relation than the two `Subset` equalities so that is definitely useful. 

As for the two subset reasoning modules, the `Setoid` version of subset reasoning should export a combinator for pointwise list equality `≋` whereas `Propositional` version of subset reasoning should not, and therefore both reasoning modules are also needed. I've reimplemented the propositional reasoning in terms of the setoid one in 20587f5d195748180864a5aa1b4d6deb45c03b34
