### ISSUE TITLE
Make Algebra heirarchy usable with instance arguments

### ISSUE THREAD

**Issue by fread2281** [agda/agda-stdlib#35]
The current `Algebra` hierarchy is parametrized by levels and not `Carrier`, thus making it hard if not impossible to use with instance arguments (like type classes). However, the equivalence relation complicates fixing this.

**Comment by MatthewDaggitt** [comment]
Changing the `Algebra` hierarchy so that it is parametrised by the carrier set would be an enormous change to how the standard library currently works and would cause _significant_ backwards compatibility issues with a large percentage of users.

Given this and the fact that the standard library does not currently make use of instance arguments, I'm afraid this looks unlikely to ever happen.
