### ISSUE TITLE
Error when running `make test`

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#363]
In the current master I got the following error:

```
$ make test
...
Whitespace violation detected in <some-path>/CHANGELOG.md.
```

**Comment by MatthewDaggitt** [comment]
Sorry about this. I think this snuck in when I was merging the CHANGELOG in the online editor on Github. I've always kind of felt that `fix-agda-whitespace` should only look at agda files, but maybe there's a reason that markdown files are included as well?

**Comment by gallais** [comment]
I think it's good practice to enforce that there is no trailing whitespace in any of
the files. Otherwise we keep polluting commits with adding / removing whitespace
(some people have emacs set up to automatically drop any trailing whitespace).

It should now be easier to maintain the invariant given that travis will (hopefully)
complain if something is broken.
