### ISSUE TITLE
Data.Nat.Properties.≤+≢⇒<

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#369]
It looks like ``≤,≢⇒<`` or ``≤and≢⇒<``  have a better mnemonic than  ``≤+≢⇒<``,
because there is no ``+`` in its type.

**Comment by mechvel** [comment]
``≤→≢→<``

**Comment by HuStmpHrrr** [comment]
I agree with this issue. `+` looks like a disjunction to be honest. otherwise, `≤×≢⇒<` is also an alternative if we want to express conjunction.

there are other modules using the same naming convention. probably it can be discussed in larger extent to make sure the naming convention makes better sense.

**Comment by MatthewDaggitt** [comment]
> there are other modules using the same naming convention. probably it can be discussed in larger extent to make sure the naming convention makes better sense.

Do you have others in mind apart from `Algebra.FunctionProperties.Consequences`?

**Comment by HuStmpHrrr** [comment]
`Data.Fin.Properties` also has `≤+≢⇒<`. I cannot find any other than this.
