### ISSUE TITLE
Cancellation for List.++

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#392]
I could not find laws stating that List.++ make a left- and right-cancellative monoid, i.e., we have
```
xs ++ ys == xs ++ zs -> ys == zs
xs ++ zs == ys ++ zs -> xs == ys
```
The second could be proven from the first by going through `reverse`, maybe:
```
xs ++ zs == ys ++ zs
reverse (xs ++ zs) == reverse (ys ++ zs)
reverse zs ++ reverse xs == reverse zs ++ reverse ys
reverse xs == reverse ys
xs == ys
```
which would need an injectivity lemma for `reverse`.

`Data.Nat.Properties` defines cancellation for addition and multiplication. 

On a related note, `List.++` is also a positive monoid, i.e. we have
```
xs ++ ys == [] -> xs == [] & ys == []
```
Such properties are also missing.  
They are defined for `Nat.+`, but not given a name, like `LeftPositive`.
I do not know what would be the most common terminology here.

**Comment by MatthewDaggitt** [comment]
> On a related note, List.++ is also a positive monoid, i.e. we have
> `xs ++ ys == [] -> xs == [] & ys == []`
> Such properties are also missing.
> They are defined for Nat.+, but not given a name, like LeftPositive.
> I do not know what would be the most common terminology here.

I agree we should settle on a standardised name for these sort of properties. Where is `LeftPositive` from? And why is it Left? The `Positive` might also be a bit confusing for numeric datatypes.

**Comment by gallais** [comment]
As usual there seems to be a few names for these: https://en.wikipedia.org/wiki/Zerosumfree_monoid

**Comment by andreasabel** [comment]
The term `Positive` is intuitive for additive monoids and thus would make sense for numeric instances.  However, for multiplicative ones we would rather speak of being free of unit dividers.

Abstractly maybe the best way is to think of the monoid operation as "composition" where the unit is the `Identity`.  Thus, positivity expresses that the identity cannot be decomposed, or is atomic.  Thus, maybe one of
- `HasAtomicIdentity` 
- `AtomicIdentity`
- `IdentityAtomic`

optionally with superscripts `l` and `r`

**Comment by JacquesCarette** [comment]
`IrreducibleIdentity` ?  Although `Atomic` does make sense, it clashes with both the notion from measure theory and from logic. Something is `Atomic` when it has *no* decompositions; here the `Identity` has a (trivial) decomposition.

**Comment by andreasabel** [comment]
At least in a monoid, `Atomic` would make sense since every element has a trivial decomposition, thus, atomicity cannot mean to have /no/decomposition.  

Officially, neither /irreducible/ nor /atomic/ maybe be attributes of units:

https://math.stackexchange.com/questions/110011/an-atom-in-boolean-algebra
> An atom is a minimal non-zero element.
> x is an atom iff for every y, either y∧x=x or y∧x=0.

https://en.wikipedia.org/wiki/Irreducible_element
> In abstract algebra, a non-zero non-unit element in an integral domain is said to be irreducible if it is not a product of two non-units. 

Thus, it is a stretch of terminology either way.

One could also say `NoInverses`, but I prefer positive statements to negative ones, and that one is rather indirect.

**Comment by andreasabel** [comment]
http://www.numericana.com/answer/groups.htm#center
The term /centerless/ comes from group theory.  /c/ is a center element if it commutes with every other element. A group is centerless if the unit is the only center element.
However, even a centerless group does not satisfy the irreducibility of the unit (no group satisfies it).
Thus, I do not like the term /centerless/ for our purposes.

Maybe `Identity(Is)Irreducible` is best.

**Comment by JacquesCarette** [comment]
You make a convincing argument that `Irreducible` is bad terminology. I agree with trying to make positive statements.

I must admit that, even though `Conical` is usually used in geometry and for additive monoids, I kind of like it because it describes a property of the monoid as a whole, and is a nice generalization of what it means to be a 'cone'. [Where `Conical` is one of the synonyms to `Positive` from https://en.wikipedia.org/wiki/Zerosumfree_monoid]

[New comment came in as I was writing] I agree that *centerless* is bad. `IdentityIsIrreducible` is a mouthful, but I would not object.

**Comment by JacquesCarette** [comment]
You can define a partial order by `x<=y` iff exist z such that `z+x = y`. And of course, `0 <= y` for all y.

The 'cone' picture comes into play when you do this on a lattice embedded in R^n -- you get a cone. Especially when you work on vector spaces, then you get an affine subspace which is literally a cone.

But most of the properties come from that partial order, not R^n.

If you take exponentials, it remains 'true' for + replaced by * and 0 replaced by 1.

So you can picture a 'cone' as being all the elements that are 'above' the unit.  Then a monoid is conical if all its non-unit elements are thus 'above' the unit.  So that (Z,+) is not conical, but (Nat, +) is.  And of course, so is (`List A`, _++_) for any type A.

**Comment by JacquesCarette** [comment]
I concur.

**Comment by alhassy** [comment]
@MatthewDaggitt `conical" - seems fine and gets lots of relevant hits`; would you please share these. I've not found any within a few seconds search, nor even after refinement by including words `algebra` or `monoid`. In constrast, `zerosumfree` *immediately* yields a helpful wiki article.

I think the choice of `conical` is somewhat reasonable, but far from ideal.

Someone navigating the standard libraries might appreciate `zerosumfree` as the property's definition is nearly in the name, whereas `conical` is suggestive of geometric properties --as indicated by nearly all of my google searches.

**Comment by MatthewDaggitt** [comment]
You're right, "conical" on its own doesn't bring anything up. I was searching "conical semigroup" and "zerosumfree semigroup".

Yes, "conical" implies some geometry but "zerosumfree" has it's own downsides. The word "sum" strongly implies additivity, but it could easily apply to the multiplicative operation of an algebra. Swings and roundabouts :smile: 

If you feel strongly that it should be called `zerosumfree` instead then go for it. I don't particularly like `_NeccessarilyIdempotentFor_`. It's not one of the four standard names, and it's a little confusing as `op NecessarilyIdempotentFor x` does not imply `op IdempotentOn x` but it sounds like it should!

**Comment by alhassy** [comment]
One does not imply the other since they are *converse* statements.

Recall that, see #421,

   `z NecessarilyIdempotentFor _∙_   =   ∀ x y → (x ∙ y) ≈ z → (x ≈ z) × (y ≈ z)`

If we now flip the final arrow, in the right hand side, we obtain 

  `∀ x y  → (x ≈ z) × (y ≈ z) → (x ∙ y) ≈ z`

Now, as `≈` is intended to be an equivalence relation, it is reasonable to instantiate `x, y` to `z, z` where the constraints are satisfied by reflexivity. The result is then the definition of the other combinator,

   `_∙_ IdempotentOn z   =  (z ∙ z) ≈ z`

Hope that helps :smile:

**Comment by MatthewDaggitt** [comment]
Thanks, that does help, and I now understand where the name comes from.

Having said that I think we're pretty decided on sticking to one of the standard names, and in practice the two reasonable candidates out of those 4 are `conical` or `zerosumfree`. Sorry!
