### ISSUE TITLE
Design of BoundedVec

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#397]
A few questions:

* Why is [`BoundedVec`](https://agda.github.io/agda-stdlib/Data.BoundedVec.html#614) abstract? To implement anything we need to go through the `View`
instead of being able to reuse functions on `Vec`.

* It is bad practice to put a computation in a return index (unless the inductive family is a
view in which case it's the whole point). So how about changing the definition to:

```agda
record BoundedVec {a} (A : Set a) (n : ℕ) : Set a where
  constructor bVec
  field {m}    : ℕ
        vec    : Vec A m
        .bound : m ≤[''] n
```

If we make `bound` irrelevant, we can use whichever order we consider the most convenient.
[`_≤″_`](https://agda.github.io/agda-stdlib/Data.Nat.Base.html#1646) would correspond to the `_+_`-based one but I'm not sure it's the easiest to use.

**Comment by MatthewDaggitt** [comment]
> Why is BoundedVec abstract?

Not sure. It is a little incongrous with the rest of the library that doesn't seem to use `abstract` much. Do you remember the reason for the original design @nad ?

@gallais your proposal looks good at first glance. I probably have a slight preference to try and avoid `_≤″_` if possible as we don't really have much infrastructure around it. Plus we've just removed it's one major use-case in the modular arithmetic library.

I also have a consistency question. We have `Data.BoundedVec` but `Data.List.NonEmpty`. Should it be `Data.Vec.Bounded` or `Data.NonEmptyList`? Actually what about `Data.Difference(Vec/List/Nat)` as well?

**Comment by gallais** [comment]
> I also have a consistency question. We have Data.BoundedVec but Data.List.NonEmpty. Should it be Data.Vec.Bounded or Data.NonEmptyList? Actually what about Data.Difference(Vec/List/Nat) as well?

I don't know. When do we decide that something is a variant on an existing datatype (`Data.List.NonEmpty` and `Data.List`) versus its own datatype (`Data.Vec` and `Data.List`)?

**Comment by JacquesCarette** [comment]
Interestingly, I see `Data.List` and `Data.List.NonEmpty` as being quite different -- `Data.List` is the 'cons' representation of the free Monoid (or Unital Semigroup), while `Data.List.NonEmpty` is the 'cons' representation of the free Semigroup.

Interestingly, I also see `Data.List` as being a `Data.Vec` which has forgotten its length.

There is no inconsistency here, as a free Monoid is naturally a graded structure.

I would either collapse all of these into the same hierarchy, or explode them all to be separate. Because depending on your approach to data-structures, you may look in quite different places to find it...  Although collapsing is theoretically more elegant, exploding is actually more user-friendly.

[In my own experimental system, the hierarchy is developed in its collapsed form, then an expander/elaborator is run as a meta-program on the library, which produces an expanded form better suited for end-users.  This is really the best of both worlds, as it eases the development burden but does not raise the burden too high for starting users.  I intend to port such an expander to Agda, to see if it is feasible there as well.]

**Comment by MatthewDaggitt** [comment]
Again not too urgent.

**Comment by MatthewDaggitt** [comment]
Now that we have `Data.Vec.Bounded` we should deprecate `Data.BoundedVec` in the next release after `agda-v2.6.1`.
