### ISSUE TITLE
Missing Data.Nat.Base and Data.List.Base in the 2.4.2.1 branch

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#52]
Please cherry-pick the commits https://github.com/agda/agda-stdlib/commit/656c248948b1a9f26d5f72f9ee013572a40ee2ab and https://github.com/agda/agda-stdlib/commit/b2ef50710f506d3bd302ed050e1f918abfa5d8dc in the 2.4.2.1 branch.

**Comment by np** [comment]
I'm doing this now and documenting also which modules can be considered basic as well given their dependencies. By doing so, I realize that Relation.Nullary.Core has no purpose anymore. Indeed Relation.Nullary only depends on Relation.Nullary.Core and thus it cannot introduce a cycle to fuse them. Because of the policy on .Core modules it means we can safely drop it, right?

**Comment by np** [comment]
Also if the user is not suppose to use the .Core module then there should be a .Base module for Char and String, which I think can safely replace the corresponding .Core modules in this case.

Comments?

**Comment by asr** [comment]
Yes, you can remove Relation.Nullary.Core.

**Comment by andreasabel** [comment]
Modifications to Char and String also approved.

**Comment by asr** [comment]
> Modifications to Char and String also approved.

I'm not sure. It seems these .Core modules really exist for avoiding cycling importations.

For example, why

    show : Char → String
    show = primShowChar

    toNat : Char → ℕ
    toNat = primCharToNat

from `Data.Char` shouldn't be in `Data.Char.Base`?

**Comment by asr** [comment]
Thanks!
