### ISSUE TITLE
Naming of Inverse-image in well founded induction

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#611]
I find this name is very hard to interpret at its first glance: https://github.com/agda/agda-stdlib/blob/master/src/Induction/WellFounded.agda#L104

After some thinking this name indeed makes sense, but it's my first time to hear "reverse image induction". Any idea for better naming? I think `Measure` would be a common usage as it is how it's called in Coq.

**Comment by MatthewDaggitt** [comment]
I'm actually planning to deprecate this module entirely. I'm of the opinion that these proofs actually belong in `Relation.Binary.Construct.On`.

**Comment by HuStmpHrrr** [comment]
hmm...

it makes sense on one hand. however, notice that it's really more about induction, instead of free relations. so we I look up induction related concept, it's hard to imagine there is something in `Relation`. I suppose induction is special in its own right and should have its own module structure.

**Comment by MatthewDaggitt** [comment]
> so when I look up induction related concept, it's hard to imagine there is something in `Relation`

Except that `Relation.Binary.Construct.On` contains all the properties about relations lifted via `on` so why wouldn't it contain well foundness proofs which is just another property after all? In fact the more I think about it, the definition of `WellFounded` should probably live in `Relation.Binary.Core` :smile:.

> I suppose induction is special in its own right and should have its own module structure.

A similar argument was made about `Relation.Binary` back when all relations about `Data.X` lived in `Relation.Binary.X` rather than `Data.X.Relation.Binary`. I think everyone is in agreement having the relations over the data live where the data in question is defined is much better. Similarly I'd argue that the properties of relations over `on` should live where the relation is defined.

I think having it's own parallel module structure for each possible well-founded construction seems unwieldy.

**Comment by HuStmpHrrr** [comment]
sure then that makes sense if all `WellFounded` stuff goes into `Relation.Binary` entirely.

**Comment by MatthewDaggitt** [comment]
Hmm this requires more changes than I've currently got time to make before the release of v1.0 (as the definitions of lexicographic ordering and transitive closure don't match up to those in `Data.Product.Relation.Binary.Lexicographic.Dependent` and `Relation.Binary.Construct.Closure.Transitive` :cry: )

**Comment by HuStmpHrrr** [comment]
I will take a look at this some time and see what's the difference.

**Comment by MatthewDaggitt** [comment]
Just realised that the module names have already been fixed. I'll close this and open a new issue for moving some of the contents.
