### ISSUE TITLE
the synonyms *0, *1 ... 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#682]
Can we  introduce the following synonyms for the properties ?
Many proofs would become considerably easier to read and write:
```
ε∙ =  proj₁ identity    -- for Monoid
∙ε =  proj₂ identity

0+ =  +-identityˡ       -- for Semiring
+0 =  +-identityʳ       --
0* = zeroˡ                 --
*0 = zeroʳ                --
1* = *-identityˡ          --
*1 =  *-identityʳ         -- 
```

**Comment by JacquesCarette** [comment]
If they were in a sub-module (so that one could choose to bring them into scope or not), I would be highly in favour. To have them there by default is a little concerning - they are so short that I worry about polluting the namespace. Otherwise, I like all of these names, and they would indeed help.

**Comment by mechvel** [comment]
1) I would like to have these _synonyms_ on the top level in the Monoid record and in Semiring record respectively.
2) If not agreed, then I ask to set this in a submodule.
3) But the situation is worse. I want to pull-request a certain code, it introduces these synonyms in the
two parametric modules. It uses widely these names. But the requirement to pull requests forbids renaming other than for avoiding an overlap. So that I am forced to spoil the readability.

**Comment by MatthewDaggitt** [comment]
I agree with @JacquesCarette that it's not desirable to have them in by default. It's very confusing for users to have a record export two different names for the same property.

Possibly they could be put in a submodule, but I'm not entirely convinced about the names themselves and whether they'll increase clarity. My natural reading of them is as functions i.e. `∙ε` seems like it should be shorthand for the function `_∙ ε`. I think it'd be much more readable if they actually spelt out the equation e.g. `x∙ε≈x`.

Another concern is keeping the code style in the standard library consistent. Even if they were added for external users, I'd probably prefer not to use them in the standard library itself in order to keep the code style consistent.

**Comment by JacquesCarette** [comment]
Perhaps call the sub-module `Convenience` (in general) as a place to put such things, for usability, but not use the in the library itself for uniformity?  Rather like the README hierarchy is meant for documentation and not direct use?

**Comment by mechvel** [comment]
So, it will be 
```
record Monoid _ _ : Set _ where
    field
       ε : Carrier
       ...
    module Convenience 
        where
         x∙ε≈x :  ...
         ...
```
This way?

**Comment by JacquesCarette** [comment]
That is a correct interpretation of the combination of my and @MatthewDaggitt 's suggestions, yes.

**Comment by MatthewDaggitt** [comment]
That is going to make the `Algebra` and `Algebra.Structures` files even less readable, especially as the syntax in the `Convenience` modules are going to have to be renamed whenever the names of operators/elements change during inheritance.

**Comment by MatthewDaggitt** [comment]
Marking this as won't fix. There's no indication that @mechvel is going to put together a PR, and to be honest I'm really very very reluctant to go down the route of having multiple names for the same proofs.
