### ISSUE TITLE
excludedMiddle 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#694]
My application library has a small module that states:  if  ``p? : Decidable P``, then there is proved the excluded middle law for  P:
```
module _ {α β} {A : Set α} {P : A → Set β} (p? : Decidable P)
  where
  excludeMiddle :  (x : A) → P x ⊎ ¬ P x
  excludeMiddle x with p? x
  ...  | yes Px  =  inj₁ Px
  ...  | no  ¬Px =  inj₂ ¬Px

  P←→¬¬P :   (x : A) → (P x ←→ (¬ ¬ P x))
  P←→¬¬P x =  ((\Px ¬Px → ¬Px Px) , from)    ...
```

Has it sense to add such to standard library?
Standard has Axiom.ExcludedMiddle.agda, but I think, the meaning of its content and its purpose is different.

**Comment by MatthewDaggitt** [comment]
I had thought it existed in `Relation.Nullary.Negation` (don't ask why!) but it turns out that we don't have such a property. The proof `excludeMiddle` should probably go in `Axiom.ExcludedMiddle`. 

The file needs some additions, @gallais suggested we probably need a type level formulation of `ExcludedMiddle` as well which would help with this proof.

**Comment by andreasabel** [comment]
Well, `Decidable P` already states that the excluded middle holds for `P`.
https://github.com/agda/agda-stdlib/blob/805c897f32f605a666ec3738a3005e3800bf2964/src/Axiom/ExcludedMiddle.agda#L21
Your function `excludedMiddle` just replaces the telling names `yes` and `no` by the non-telling names of the injections into the disjoint sum type.
