### ISSUE TITLE
Policy on generalised variables

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#697]
The new `variable` keyword has the potential to get rid of a lot of the anonymous modules that are scattered about the library. Thought I should start a discussion about how best to go about using it.

Two main questions immediately spring to mind I guess:

1. What should be put under `variable` and what should be left in the type

In my opinion we should definitely generalise universe levels and sets. After that it becomes a little less obvious to me what should and shouldn't be generalised. Although it might be tempting to generalise everything possible, it might be possible that going overboard will impact readability. For example I'm wondering if the type signature:
```
filter : Decidable {A = A} P → List A → List A
```
is more or less clear than:
```
filter : ∀ {P : Pred A p} → Decidable P → List A → List A
```

2. Should we have a central module of generalised variables or should they be local to each file?

Variables are exported by modules so in the former case the generalised variable file could act as a style guide. However I suspect that such a setup isn't flexible enough and we'd still have to add local variable declarations to each file. In the latter case I guess we have add a section to the prelude of each file where we declare variables in a private scope?

**Comment by JacquesCarette** [comment]
On `filter`, I definitely prefer the second signature. The first asks me to remember too much about what the arguments to `Decidable` are; and the need to specify an implicit also seems to lean in that direction.

Also, before jumping on this, I think it is indispensable to have some kind of emacs command where, when you hover (or select?) a function name, you get its **full** signature.

For second, to me it's clear already in the question: you want a file full of **globals**, seriously?

Both anonymous modules and variables have a common problem: they make reading the library a "whole file" affair, rather than being able to jump to where the function is actually defined. In some ways, "jump to definition" of a function should jump where the definition starts, which is now logically at the first module/variable declaration...

Also note that Coq uses sections to separate things -- in other words, they mix modules (anonymous and otherwise) and variables. So there is likely a lesson in that too.

**Comment by MatthewDaggitt** [comment]
> For second, to me it's clear already in the question: you want a file full of globals, seriously?

Isn't that the point of most of the library? :stuck_out_tongue: Haha, but yes I agree with you. Thought I'd raise it as a possible design decision just in case.

> Both anonymous modules and variables have a common problem: they make reading the library a "whole file" affair, rather than being able to jump to where the function is actually defined. In some ways, "jump to definition" of a function should jump where the definition starts, which is now logically at the first module/variable declaration...

> Also note that Coq uses sections to separate things -- in other words, they mix modules (anonymous and otherwise) and variables. So there is likely a lesson in that too.

I agree, we definitely don't want to go overboard on the variables and sub-modules have their place as well.

> Also, before jumping on this, I think it is indispensable to have some kind of emacs command where, when you hover (or select?) a function name, you get its full signature.

That does sound very desirable. It'd probably be worth opening an issue on the main Agda repository about it. Would you be on board with a policy of **only** generalising levels and sets in the mean time? That would already simplify a lot of code and I don't think e.g. `map : (A → B) → List A → List B` is asking too much of users... Indeed many users have been asking for a while for the ability to write just that.

**Comment by JacquesCarette** [comment]
Yes, I agree (and not enough people think of it that way!) that the whole point of a library is to be full of globals!  But I guess those ought to be carefully named, explicit globals with 'meaning'.

I agree that that signature for `map` is highly desirable. So starting with levels and sets seems like a 'safe' start. Especially as it might also reveal some outstanding bugs with the feature...

**Comment by MatthewDaggitt** [comment]
The style guide has been updated with the policy agreed upon so I'm closing this now.
