### ISSUE TITLE
Implementation of `_<_` in `Data.Integer` results in unsolved metas

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#746]
Unfortunately the definition of `_<_` in `Data.Integer` is not ideal as Agda often can't infer the first argument because it's implemented in terms of `suc` -> `_+_` -> `_⊖_` . This means that one often has to provide implicit arguments when using many of the common proofs (e.g. `<-trans` always needs to be given as `(λ {i} → <-trans {i})`).

This could be fixed by redefining it as:
```agda
data _<_ : ℤ → ℤ → Set where
  -<+ : ∀ {m n} → -[1+ m ] < + n
  -<- : ∀ {m n} → (n<m : n ℕ.< m) → -[1+ m ] < -[1+ n ]
  +<+ : ∀ {m n} → (m<n : m ℕ.< n) → + m < + n
```
Obviously this is a fairly large non-backwards compatible change in the API. There are two options:
1. Leave it to the mythical v2.0 (whenever that is).
2. Add it now as a new relation `_<′_` with the understanding that they'll be swapped at v2.0
3. Add it now as `_<_` and deprecate the old one, renaming it to `_<′_` 

Any thoughts?

Edit: I should add the current definition is also a nightmare to prove anything about due to the long chain in the definition.

**Comment by JacquesCarette** [comment]
My thinking is that option 3 is best.  Reasoning: we're still learning how to encode proofs properly in a DTL, especially a DTL that is proof-relevant. So even though some proofs are correct and 'equivalent' to others doesn't mean they are "good" proofs. Turns out the current short-cut for `_<_` is one of those cases.

Agda is still fairly young, so that it is still possible to do some breaking changes. Yes, this does annoy the current user base, but the number of people affected is not huge.  As the system gains popularity, such breaking changes get harder and harder to make (the system's community acts as inertia), and then early 'bad' designs can no longer be fixed without causing a lot of fuss. Furthermore, competing systems (if they are smart), will learn from these mistakes.  [This is not just theory: I've seen it happen first-hand to CAS.]
