### ISSUE TITLE
"make test" requires --without-K --safe

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#758]
I have cloned "master", added there the file Prelude0.agda, removed Bin.agda, 
replaced ``Bin/* `` with a single file ``Bin/Bin0.agda``.
Then made
```
> make clean
> fix-agda-whitespace
> make test
```
1) If the header ``-- The Agda standard library ...`` 
is forgotten in Prelude0.agda, then it reports of a wrong Everything.agda, without reporting 
of the reason.
2) After the header is set, ``test`` reports about that neither --safe nor --unsafe is set in the file.
Is not ``safe`` a default?
Then I add ``--safe``. And it complains about absence of ``--without-K``.
So I add ``--without-K --safe``, and now ``test`` succeeds.

But what does it mean ``--safe`` ? I suspect that in my library everything is safe.
Why do I need ``--without-K`` ? 
In my library, these two options are not mentioned, and it works under Agda 2.6.0 lib-1.0.
Once I tried to set  ``--without-K --safe`` everywhere.
But a) It is not type-checked as a whole,
 b) when I set it to some files and not to others, then there is not any difference in the cost of type checking. 

Please, advise.

**Comment by gallais** [comment]
Thanks for the feedback, I'll try to make the script's error messages more helpful.

> Is not safe a default?

It is not. Unless you have explicitly added `--safe` at the top of the file, Agda
will accept unsafe features (e.g. combining sized types and guardedness-based
termination checking for codata which is inconsistent).

In the standard library we expect all the modules to be tagged as `--safe` unless
they are not actually safe. They then need to be explicitly mentioned in the list
of `unsafeModules` in `GenerateEverything.hs` file (this way if people just forget
to add `--safe` they are told off instead of us just assuming the module is unsafe).

> Why do I need `--without-K`

`--without-K` is more restrictive than `--with-K` and is needed for compatibility
with `--cubical` for instance. Just like we have separated unsafe features from
safe ones so that user can use the library and still write safe code, we have tried
to isolate results which rely on the axiom K so that people who don't want to assume
it can still rely on the library.

**Comment by mechvel** [comment]
It forces me to add ``--without-K --safe`` everywhere.
I expect that this will lead to the type-check fail at some stage of accommodating  and merging the modules from BFLib-0.1 (I have seen this effect, and then removed this options).
But let us wait and see the effects, if they occur.
