### ISSUE TITLE
Is  _Respects₂_  sufficient?  

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#8]
I have a question about `Relation.Binary.Core._Respects₂_`

It  is defined so that it is difficult to use. Normally, the programmer needs to write
```agda
 ~resps≈  x≈x'  y≈y'  x~y        -- (1)
```
for deriving `x' ~ y'` from `x ≈ x'`, `y ≈ y'` and `x ~ y` where `~resps≈  :   _~_  Respects₂'  _≈_`

Without using `Respects₂' (defined in an evident way), what may be a simple expression for (1)?
Am I missing something?

**Comment by MatthewDaggitt** [comment]
Very old issue but still outstanding I think. I would second this, as the new form proposed above is far more convenient to use. 

The current form is particularly irritating if the relation `~` is not transitive as you can no longer perform dual substitution. 

The proposed `Respects₂'` would require reflexivity of '_≈_' in order to recover the current `Respects₂` so the current form probably shouldn't be replaced. However would anyone object to the new form being added?

**Comment by MatthewDaggitt** [comment]
@mechvel I agree with you, your form is definitely easier to work with and if the library was redesigned from the bottom up we'd use yours. However the current form is usable, and in my opinion adding a ticked version will result in more confusion than time saved, and we'll end up with conversion lemmas everywhere.

I've added `<-respˡ-≈` and `<-respʳ-≈` proofs to the record hierarchies in bfd3636d89f7856ce413bd3d34f311cac479186f. This should make the existing form much easier to use as you no longer have to mess around with projecting them out.

Given that I'm afraid I'm closing this issue. I hope the new proofs help.
