### ISSUE TITLE
Partial Equivalence Relations and Partial Setoids

### ISSUE THREAD

**Issue by TOTBWF** [agda/agda-stdlib#842]
PERS and Partial Setoids are very useful when doing reasoning about subsets of types. I propose that we add both to the standard library. I have a (admittedly very naive) example over at https://github.com/TOTBWF/agda-partial-setoid.

**Comment by MatthewDaggitt** [comment]
Thanks for the suggestion. Very neat, I've never come across that particular formalisation of subsets before.

I'm a bit unsure about including the definitions in `Relation.Binary` because the exposed type parameter in `PartialSetoid` is inconsistent with the rest of the hierarchy. I guess we can either hide the type parameter (and redefine `_∈_` using a pattern synonym to reverse the order of the arguments) or put it in it's own file. @JacquesCarette, might you have an opinion about this?

**Comment by TOTBWF** [comment]
I'm not particularly happy with the exposed type parameter either. The issue isn't so much `_∈_`, but rather `_⊆_`, as you need to make sure that both partial setoids are defined over the same carrier type. If someone has some insight on this, it would be greatly appreciated 🙂

**Comment by TOTBWF** [comment]
For some further motivation on this, see https://github.com/TOTBWF/agda-partial-setoid/blob/master/src/Algebra/Morphism/Properties.agda where I use this to prove that a group homomorphism is injective if and only if the kernel is trivial.

**Comment by JacquesCarette** [comment]
I'm certainly interested in partial Setoids -- I recently came across 
https://arxiv.org/abs/1902.06109
On Group-Like Magmoids
Dan Jonsson
(Submitted on 16 Feb 2019 (v1), last revised 6 May 2019 (this version, v3))

    A magmoid is a non-empty set with a partial binary operation; group-like magmoids generalize group-like magmas such as semigroups, monoids and groups. In this article, we first consider the many ways in which the notions of associative multiplication, identities and inverses can be generalized when the total binary operation is replaced by a partial binary operation. Poloids, groupoids, skew-poloids, skew-groupoids, prepoloids, pregroupoids, skew-prepoloids and skew-pregroupoids are then defined in terms of generalized associativity, generalized identities and generalized inverses. Some basic results about these magmoids are derived, and connections between poloid-like and prepoloid-like magmoids, in particular semigroups, are described. Notably, analogues of the Ehresmann-Schein-Nampooribad theorem are proved. 

which is quite full of "partial" stuff. Of a different kind than the ones here.

Right now, I'm having a hard time seeing the real impact on stdlib, as the repo pointed to contains copies, so I can't easily see what's changed (no easy way to do a 'diff', unlike what a PR would enable).

Because going 'partial' can be very pervasive, my feeling is that the default Algebra hierarchy should stay total, but that there also ought to be a parallel one that allows equivalence relations to be partial. [Though I'm willing to be convinced that merging this in wouldn't be too compatibility-breaking, so can be done as a deep merge]

**Comment by TOTBWF** [comment]
If you would like, I could open a draft PR rather than work in a separate repository. I could totally see how doing a mental diff of the two would be rather tricky.

On the parallel algebraic hierarchy, I can definitely see arguments for both. On one hand, there would be quite a few breaking changes, but they would be rather easy to fix. Furthermore, having a separate partial hierarchy would make dealing with algebraic substructures rather tricky. You could "lift" proofs about the partial algebras to their total counterparts by just supplying `refl`, but going the other way is not possible, and would result in a bunch of duplicated proofs. However, there would be quite a few breaking changes, which would make life potentially tricky for users.

**Comment by JacquesCarette** [comment]
A draft PR, along with all the fixes needed to make the while library work after the changes, would make evaluation of the 'deep merge' much easier to discuss with full knowledge of the impact.

substructures are very tricky indeed. Especially in constructive type theory.

**Comment by MatthewDaggitt** [comment]
This was added in #847
