### ISSUE TITLE
import list in  Relation.Binary.Construct.StrictToNonStrict

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#912]
* The head module import names are not in alphabetical order.
* Six modules are imported after "module ... where", while they do not use any parameter from     
  module Relation.Binary.Construct.StrictToNonStrict ...

Similar it is with   Relation.Binary.Properties.StrictTotalOrder.

Needs this to be corrected?

**Comment by MatthewDaggitt** [comment]
> The head module import names are not in alphabetical order.

Ideally they would be, but it's not the end of the world if they're not. If you'd like to submit a PR to fix them then go ahead, but I don't think it'll get fixed otherwise.

> Six modules are imported after "module ... where", while they do not use any parameter from
module Relation.Binary.Construct.StrictToNonStrict ...

That actually obeys the [style guide](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md#module-imports) for the library so shouldn't be changed, without changing it everywhere. I agree with you in that in my own libraries I tend to put non parameterised imports above the module declaration as I think it's easier to read...

**Comment by MatthewDaggitt** [comment]
Until we have a linter for Agda, I can't see this getting fixed consistently across the library so I'm going to close this.
