### ISSUE TITLE
Function.Equivalence cannot be used when Function is imported

### ISSUE THREAD

**Issue by uzytkownik** [agda/agda-stdlib#986]
Currently this code doesn't work

```
open import Function using (_∘_)
open import Function.Equivalence using (_⇔_; equivalence)
```

As agda complains that module `Function.Equivalence` and record `Function.Bundle.Equivalence` have the same name. A workaround is to reverse order (not nice if you want to keep imports alphabetical) or use Function.Core (which is recommended against by documentation).

**Comment by MatthewDaggitt** [comment]
I agree, this is slightly unfortunate. The short-term answer is to import `Function.Base` instead of `Function`. In the long-term we're planning on deprecating and eventually removing `Function.Equivalence` entirely.

That just leaves the medium term! It's weird that it works one way round and not the other. It feels like it should either work for both orders or fail for both. I might be tempted to ask a question on the mailing list or open an issue on the main Agda repository asking why this is.

**Comment by MatthewDaggitt** [comment]
Fixed by deprecating the old function hierarchy as discussed in https://github.com/agda/agda-stdlib/issues/759
